### ISSUE TITLE
Shares namespace with MessageBus

### ISSUE THREAD

**Issue by mikz** [lowjoel/message_bus-client#5]
This gem can't be loaded together with `message_bus`. Loading this gem will cause `message_bus` to crash:

```
ArgumentError (wrong number of arguments (given 2, expected 1)):
  message_bus-client (0.1.0) lib/message_bus/client/message_handler.rb:29:in `subscribe'
  message_bus (2.0.2) lib/message_bus/rack/middleware.rb:104:in `block in call'
  message_bus (2.0.2) lib/message_bus/rack/middleware.rb:100:in `each'
  message_bus (2.0.2) lib/message_bus/rack/middleware.rb:100:in `call'
```

Because it redefines `MessageBus::Client`.

This gem should not reuse `MessageBus` namespace and use its own to prevent conflicts.

**Comment by lowjoel** [comment]
Wow. This is painful. I imagine that most related gems share namespaces instead of making them disjoint. I can't seem to think of any alternative that does not require a renaming of the gem. I'll have to consider this further.

However, feel free to rename it as you'd like for your own use in the meanwhile.
